import sys
import yaml
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "data" / "types.yml"
TARGET = ROOT / "reference" / "glossary.qmd"

HEADER = """---
title: "Glossary"
subtitle: "The type registry, rendered from `data/types.yml`"
---

This page is generated by `tools/gen-glossary.py` from `data/types.yml`. The
registry is the single source of truth; this file is a deterministic projection
of it. Edit the data, not this page.

"""


def anchor(name):
    return name.lower()


def section(title, rows):
    out = [f"## {title}\n"]
    for t in rows:
        out.append(f"### {t['name']} {{#{anchor(t['name'])}}}\n")
        out.append(f"`{t['assembly']}`\n")
        out.append(f"{t['summary']}\n")
        if t.get("replacement"):
            out.append(f"> Use instead: `{t['replacement']}`\n")
        out.append("")
    return "\n".join(out)


def main():
    registry = yaml.safe_load(REGISTRY.read_text())
    types = sorted(registry["types"], key=lambda t: t["name"].lower())
    live = [t for t in types if t["status"] == "live"]
    dead = [t for t in types if t["status"] == "dead"]
    body = HEADER
    body += section("Live", live) + "\n"
    body += section("Dead", dead)
    TARGET.write_text(body.rstrip() + "\n")
    print(f"wrote {TARGET} ({len(live)} live, {len(dead)} dead)")


if __name__ == "__main__":
    sys.exit(main())
